name: emisyon_standartlari_cep_rehberi
description: Emisyon İmisyon Ölçüm Standartları offline APK cep rehberi.
publish_to: 'none'
version: 0.3.6+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/standards.json
    - assets/standards_extra.json
    - assets/standards_overrides.json
    - assets/education_notes.json
    - assets/education_notes_extra.json
    - assets/visual_notes.json
    - assets/visual_notes_extra.json
    - assets/visuals/
